// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDutS1DXeOup31zsMZ2MIui-o25NOtEqE',
    appId: '1:990347792416:web:2ec3513d9bc7f11685ec45',
    messagingSenderId: '990347792416',
    projectId: 'todo-ea25e',
    authDomain: 'todo-ea25e.firebaseapp.com',
    storageBucket: 'todo-ea25e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBUMpHgfe1044lIsaJ5Atr1cxJ8QAGS_k',
    appId: '1:990347792416:android:c63a4ed6a1dd464f85ec45',
    messagingSenderId: '990347792416',
    projectId: 'todo-ea25e',
    storageBucket: 'todo-ea25e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsThJpsHnWzmuH1DMWwPtXm8pzaJYJFT0',
    appId: '1:990347792416:ios:17e5a306097d558285ec45',
    messagingSenderId: '990347792416',
    projectId: 'todo-ea25e',
    storageBucket: 'todo-ea25e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsThJpsHnWzmuH1DMWwPtXm8pzaJYJFT0',
    appId: '1:990347792416:ios:17e5a306097d558285ec45',
    messagingSenderId: '990347792416',
    projectId: 'todo-ea25e',
    storageBucket: 'todo-ea25e.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDutS1DXeOup31zsMZ2MIui-o25NOtEqE',
    appId: '1:990347792416:web:ee59a524e9e1423185ec45',
    messagingSenderId: '990347792416',
    projectId: 'todo-ea25e',
    authDomain: 'todo-ea25e.firebaseapp.com',
    storageBucket: 'todo-ea25e.appspot.com',
  );
}
